version: "3.9"

services:
  db:
    image: postgres:16.11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: rails server -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data: